name: my-first-pipeline

# Define where the pipeline should run
on: # on is trhe trigger
  push: # run pipeline when someone pushes code
    branches: # pipeline only run on these branches
      - main
      - develop
      - staging
  pull_request:
    branches:
      - main
      - develop
      - staging

env:
  APP_NAME: "myapp"
  REGION: "us-east-1"


jobs: 
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files in repo
        run: ls -R

      - name: Check for response on build
        run: echo "Building the app - checking..."

      - name: Building Docker fake Image
        run: echo "Running tests... "
      - name: Build Docker image
        run: docker build -t $APP_NAME .

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin

      - name: Scan Docker image with Trivy
        run: trivy image --severity CRITICAL --exit-code 0 --no-progress $APP_NAME

  security-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Checkov (Terraform/IaC scanner)
        run: |
          pip install checkov

      - name: Run Checkov on repo
        run: |
          checkov -d . || echo "Checkov finished with findings"

      - name: Install Gitleaks (secret scanner)
        run: |
          curl -sSfL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_linux_x64.tar.gz -o gitleaks.tar.gz
          tar -xzf gitleaks.tar.gz gitleaks
          sudo mv gitleaks /usr/local/bin/gitleaks


      - name: Run Gitleaks secret scan
        run: |
          gitleaks detect --no-banner --redact || echo "Gitleaks finished with findings"
